;EJERCICIO 3 
;LEA EL PB, LE RESTE 0X3C Y LA MAGNITUD DEL RESULTADO SALGA POR EL PC
;AL HABER UN PUERTO DE SALIDA, DE ORIGEN SAQUE 0X00

			INCLUDE 	<ENCABEZADO.INC>
			CLRF		TRISC
			BCF			STATUS,RP0		;B0
REPITE:		MOVLW 		0X3C
			SUBWF		PORTC,W
			BTFSS		STATUS,C		;ES >0 RES?
			SUBLW 		.0
			MOVWF		PORTC
			GOTO 		REPITE

			
			
;SUBWF	F,D 	RESUL = REG - W
;				RESUL = REG + C2(W)			

;AL HACER UNA RESTA 
;SI EL BIT DE ACARREO SE PONE EN 1,EL RESULTADO ES CERO O POSITIVO
;SI EL BIT DE ACARREO SE PONE EN 0,EL RESULTADO ES NEGATIVO
			
;SUBLW 	K 		W = K - W
;				W = K + C2(W)
;SI K=0			W = 0 + C2(W)
;				W = C2(W)
			END
			