;EJERCICIO 2 
;LEA EL PB, LE SUME 0X54 Y EL RESULTADO SALGA POR EL PC 
;AL HABER UN PUERTO DE SALIDA, DE ORIGEN SAQUE 0X00

			INCLUDE		<ENCABEZADO.INC>
			CLRF		TRISC
			BCF			STATUS,RP0		;B0
			MOVF		PORTB,W
			ADDLW		0X02
			MOVWF		PORTC
			GOTO		$-3
			END