SUBT1V:			MACRO		VAR1
				MOVLW		VAR1
				MOVWF		0X60
				CALL		ST1V
				ENDM
;****************************
SUBT2V:			MACRO		VAR1,VAR2
				MOVLW		VAR1
				MOVWF		0X61
				MOVLW		VAR2
				MOVWF		0X62
				CALL		ST2V
				ENDM
;****************************
SUBT3V:			MACRO		VAR1,VAR2,VAR3
				MOVLW		VAR1
				MOVWF		0X64
				MOVLW		VAR2
				MOVWF		0X65
				MOVLW		VAR3
				MOVWF		0X66
				CALL		ST3V
				ENDM
;****************************
PUSH_ANTIR:		MACRO		PUERTO,PIN
				BTFSS		PUERTO,PIN
				GOTO		$-1
				CALL		T25MS
				BTFSC		PUERTO,PIN
				GOTO		$-1
				CALL		T25MS
				ENDM




;MOTOR EN SENTIDO ANTIHORARIO
;DEPENDIENDO DE LAS CARACTERISTICAS DE NUESTRO MOTOR (BIPOLAR O UNIPOLAR) SE SELECCIONA UNA CONFIGURACION
;EN ESTE CASO DECIDIMOS USAR MEDIO PASO PARA TENER UNA MAYOR PRECISI�N.
;RECORDEMOS QUE LAS SALIDAS DEL PORTC SE CONECTAN A NUESTRO CONTROLADOR QUE A SU VEZ ESTE CONTROLA LA ACTIVACION
;DE LAS BOBINAS INTERNAS DE NUESTRO MOTOR.

										;PUERTO C SALIDAS
PIZQ:			MACRO					;C3		C2		C1		C0
				MOVLW 		0X08		;1		0		0		0
				MOVWF		PORTC		
				CALL		T10MS		;FRECUENCIA M�XIMA A LA QUE TRABAJA EL MOTOR
				MOVLW 		0X0C		;1		1		0		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X04		;0		1		0		0	
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X06		;0		1		1		0		
				MOVWF		PORTC	
				CALL		T10MS
				MOVLW 		0X02		;0		0		1		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X03		;0		0		1		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X01		;0		0		0		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X09		;1		0		0		1
				MOVWF		PORTC
				ENDM

;MOTOR EN SENTIDO HORARIO

PDER:			MACRO
				MOVLW 		0X09		;1		0		0		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X01		;0		0		0		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X03		;0		0		1		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X02		;0		0		1		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X06		;0		1		1		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X04		;0		1		0		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X0C		;1		1		0		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X08		;1		0		0		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X09		;1		0		0		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X01		;0		0		0		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X03		;0		0		1		1
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X02		;0		0		1		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X06		;0		1		1		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X04		;0		1		0		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X0C		;1		1		0		0
				MOVWF		PORTC
				CALL		T10MS
				MOVLW 		0X08		;1		0		0		0
				MOVWF		PORTC
				CALL		T10MS
				ENDM

APAGADO:		MACRO
				CLRF		PORTC		;LIMPIA EL PUERTO C
				ENDM

